# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Satyajit Sarangi"
subtitle: "See the world through my eyes!"
author: "Satyajit Sarangi"
header:
 title: "Photography"
 subtitle: "by Satyajit Sarangi"
footer:
 name: "Hey there, my name is Satyajit."
 bio: "I am a developer and a tech aficionado. I am an amateur photographer."
 github: "github.com/ssarangi"
web_design: "SS"
social_urls:
  facebook: "https://www.facebook.com/satyajitsarangi"
  twitter: "https://www.twitter.com/ssarangi"
  instagram: "https://www.instagram.com/satyajit.sarangi"
  linkedin: "https://linkedin.com/satyajitsarangi"
  github: "https://www.github.com/ssarangi"
